;--------------------------------------------------------------------------
; Storage Manager
;--------------------------------------------------------------------------
[Storage]
Storage_NAS_GENERAL
Storage_NAS_FS_LIST

[Storage_NAS_GENERAL]
SYS_ID=<CHANGE><ENIQ_POOL_ID>
POOL_PRI=<CHANGE><ENIQ_POOL_ID>
POOL_SEC=<CHANGE><ENIQ_SEC_POOL_ID>

[Storage_NAS_FS_LIST]
Storage_NAS_ADMIN
Storage_NAS_ARCHIVE
Storage_NAS_BACKUP
Storage_NAS_EVENTDATA_00
Storage_NAS_EVENTDATA_01
Storage_NAS_EVENTDATA_02
Storage_NAS_EVENTDATA_03
Storage_NAS_REJECTED
Storage_NAS_HOME
Storage_NAS_LOG
Storage_NAS_MEDIATION_SW
Storage_NAS_MEDIATION_INTER
Storage_NAS_NORTHBOUND
Storage_NAS_REFERENCE
Storage_NAS_SENTINEL
Storage_NAS_SW
Storage_NAS_UPGRADE

[Storage_NAS_ADMIN]
FS_NAME=admin
FS_SIZE=2g
NFS_HOST=nas1
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-admin
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/admin
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=create_admin_dir
OWNER=dcuser
GROUP=dc5000

[Storage_NAS_ARCHIVE]
FS_NAME=archive
FS_SIZE=8g
NFS_HOST=nas5
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-archive
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/archive
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform
OWNER=dcuser
GROUP=dc5000

[Storage_NAS_BACKUP]
FS_NAME=backup
FS_SIZE=768g
NFS_HOST=nas1
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-backup
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/backup
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform
OWNER=dcuser
GROUP=dc5000

[Storage_NAS_EVENTDATA_00]
FS_NAME=eventdata/00
FS_SIZE=30g
NFS_HOST=nas1
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-eventdata-00
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/data/pmdata/eventdata/00
NFS_SHARE_OPTIONS="rw,async,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform
OWNER=dcuser
GROUP=dc5000

[Storage_NAS_EVENTDATA_01]
FS_NAME=eventdata/01
FS_SIZE=30g
NFS_HOST=nas5
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-eventdata-01
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/data/pmdata/eventdata/01
NFS_SHARE_OPTIONS="rw,async,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform
OWNER=dcuser
GROUP=dc5000

[Storage_NAS_EVENTDATA_02]
FS_NAME=eventdata/02
FS_SIZE=30g
NFS_HOST=nas2
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-eventdata-02
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/data/pmdata/eventdata/02
NFS_SHARE_OPTIONS="rw,async,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform
OWNER=dcuser
GROUP=dc5000

[Storage_NAS_EVENTDATA_03]
FS_NAME=eventdata/03
FS_SIZE=30g
NFS_HOST=nas6
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-eventdata-03
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/data/pmdata/eventdata/03
NFS_SHARE_OPTIONS="rw,async,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform
OWNER=dcuser
GROUP=dc5000

[Storage_NAS_REJECTED]
FS_NAME=rejected
FS_SIZE=2g
NFS_HOST=nas2
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-rejected
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/data/rejected
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform
OWNER=dcuser
GROUP=dc5000

[Storage_NAS_HOME]
FS_NAME=home
FS_SIZE=10g
NFS_HOST=nas1
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-home
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/home
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=create_users
OWNER=dcuser
GROUP=dc5000

[Storage_NAS_LOG]
FS_NAME=log
FS_SIZE=30g
NFS_HOST=nas6
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-log
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/log
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=ALL
OWNER=dcuser
GROUP=dc5000

[Storage_NAS_MEDIATION_SW]
FS_NAME=mediation_sw
FS_SIZE=4g
NFS_HOST=nas5
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-mediation_sw
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/mediation_sw
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform
OWNER=dcuser
GROUP=dc5000

[Storage_NAS_MEDIATION_INTER]
FS_NAME=mediation_inter
FS_SIZE=40g
NFS_HOST=nas5
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-mediation_inter
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/mediation_inter
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform
OWNER=dcuser
GROUP=dc5000

[Storage_NAS_NORTHBOUND]
FS_NAME=northbound
FS_SIZE=100g
NFS_HOST=nas5
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-northbound
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/northbound
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=create_directories
OWNER=dcuser
GROUP=dc5000

[Storage_NAS_REFERENCE]
FS_NAME=reference
FS_SIZE=2g
NFS_HOST=nas2
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-reference
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/data/reference
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform
OWNER=dcuser
GROUP=dc5000

[Storage_NAS_SENTINEL]
FS_NAME=sentinel
FS_SIZE=2g
NFS_HOST=nas6
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-sentinel
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/sentinel
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=relocate_sentinel
OWNER=dcuser
GROUP=dc5000

[Storage_NAS_SW]
FS_NAME=sw
FS_SIZE=2g
NFS_HOST=nas6
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-sw
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/sw
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=create_directories
OWNER=dcuser
GROUP=dc5000

[Storage_NAS_UPGRADE]
FS_NAME=upgrade
FS_SIZE=3g
NFS_HOST=nas1
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-upgrade
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/upgrade
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=ALL
OWNER=dcuser
GROUP=dc5000
