;--------------------------------------------------------------------------
; Storage Manager
;--------------------------------------------------------------------------
[Storage]
Storage_NAS_GENERAL
Storage_NAS_FS_LIST

[Storage_NAS_GENERAL]
SYS_ID=<CHANGE><ENIQ_POOL_ID>
POOL_PRI=<CHANGE><ENIQ_POOL_ID>
POOL_SEC=<CHANGE><ENIQ_SEC_POOL_ID>

[Storage_NAS_FS_LIST]
Storage_NAS_ADMIN
Storage_NAS_ARCHIVE
Storage_NAS_BACKUP
Storage_NAS_ETLDATA
Storage_NAS_ETLDATA_00
Storage_NAS_ETLDATA_01
Storage_NAS_ETLDATA_02
Storage_NAS_ETLDATA_03
Storage_NAS_FMDATA
Storage_NAS_HOME
Storage_NAS_LOG
Storage_NAS_PMDATA
Storage_NAS_REFERENCE
Storage_NAS_REJECTED
Storage_NAS_SENTINEL
Storage_NAS_SNAPSHOT
Storage_NAS_SQL_ANYWHERE
Storage_NAS_SYBASE_IQ
Storage_NAS_SW
Storage_NAS_UPGRADE
Storage_NAS_PMDATA_SOEM
Storage_NAS_PMDATA_SIM

[Storage_NAS_ADMIN]
FS_NAME=admin
FS_SIZE=2g
NFS_HOST=nas1
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-admin
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/admin
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=create_admin_dir

[Storage_NAS_ARCHIVE]
FS_NAME=archive
FS_SIZE=16g
NFS_HOST=nas5
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-archive
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/archive
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform

[Storage_NAS_BACKUP]
FS_NAME=backup
FS_SIZE=150g
NFS_HOST=nas1
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-backup
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/backup
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform

[Storage_NAS_ETLDATA]
FS_NAME=etldata
FS_SIZE=100g
NFS_HOST=nas2
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-etldata
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/data/etldata
NFS_SHARE_OPTIONS="rw,async,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform

[Storage_NAS_ETLDATA_00]
FS_NAME=etldata_/00
FS_SIZE=100g
NFS_HOST=nas3
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-etldata_-00
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/data/etldata_/00
NFS_SHARE_OPTIONS="rw,async,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform
OWNER=dcuser
GROUP=dc5000

[Storage_NAS_ETLDATA_01]
FS_NAME=etldata_/01
FS_SIZE=100g
NFS_HOST=nas7
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-etldata_-01
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/data/etldata_/01
NFS_SHARE_OPTIONS="rw,async,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform
OWNER=dcuser
GROUP=dc5000

[Storage_NAS_ETLDATA_02]
FS_NAME=etldata_/02
FS_SIZE=100g
NFS_HOST=nas4
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-etldata_-02
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/data/etldata_/02
NFS_SHARE_OPTIONS="rw,async,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform
OWNER=dcuser
GROUP=dc5000

[Storage_NAS_ETLDATA_03]
FS_NAME=etldata_/03
FS_SIZE=100g
NFS_HOST=nas8
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-etldata_-03
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/data/etldata_/03
NFS_SHARE_OPTIONS="rw,async,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform
OWNER=dcuser
GROUP=dc5000

[Storage_NAS_FMDATA]
FS_NAME=fmdata
FS_SIZE=1g
NFS_HOST=nas2
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-fmdata
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/fmdata
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform

[Storage_NAS_HOME]
FS_NAME=home
FS_SIZE=10g
NFS_HOST=nas1
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-home
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/home
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=create_users

[Storage_NAS_LOG]
FS_NAME=log
FS_SIZE=150g
NFS_HOST=nas6
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-log
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/log
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=ALL

[Storage_NAS_PMDATA]
FS_NAME=pmdata
FS_SIZE=5g
NFS_HOST=nas2
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-pmdata
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/data/pmdata
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=create_directories

[Storage_NAS_REFERENCE]
FS_NAME=reference
FS_SIZE=5g
NFS_HOST=nas2
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-reference
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/data/reference
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform

[Storage_NAS_REJECTED]
FS_NAME=rejected
FS_SIZE=10g
NFS_HOST=nas2
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-rejected
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/data/rejected
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform

[Storage_NAS_SENTINEL]
FS_NAME=sentinel
FS_SIZE=1g
NFS_HOST=nas6
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-sentinel
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/sentinel
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=relocate_sentinel

[Storage_NAS_SNAPSHOT]
FS_NAME=snapshot
FS_SIZE=1g
NFS_HOST=nas5
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-snapshot
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/snapshot
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=ALL

[Storage_NAS_SQL_ANYWHERE]
FS_NAME=sql_anywhere
FS_SIZE=2g
NFS_HOST=nas1
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-sql_anywhere
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/sql_anywhere
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=install_sybase_asa

[Storage_NAS_SYBASE_IQ]
FS_NAME=sybase_iq
FS_SIZE=5g
NFS_HOST=nas2
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-sybase_iq
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/sybase_iq
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=install_sybaseiq

[Storage_NAS_SW]
FS_NAME=sw
FS_SIZE=10g
NFS_HOST=nas6
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-sw
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/sw
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=create_directories

[Storage_NAS_UPGRADE]
FS_NAME=upgrade
FS_SIZE=3g
NFS_HOST=nas1
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-upgrade
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/upgrade
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=ALL

[Storage_NAS_PMDATA_SOEM]
FS_NAME=pmdata_soem
FS_SIZE=1g
NFS_HOST=nas7
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-pmdata_soem
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/data/pmdata_soem
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform

[Storage_NAS_PMDATA_SIM]
FS_NAME=pmdata_sim
FS_SIZE=40g
NFS_HOST=nas8
SHARE_PATH=/vx/<CHANGE><ENIQ_POOL_ID>-pmdata_sim
MOUNT_PATH=<CHANGE><ENIQ_BASE_DIR>/data/pmdata_sim
NFS_SHARE_OPTIONS="rw,no_root_squash"
SNAP_TYPE=optim
STAGE=install_ENIQ_platform
